hw-02-finish
Elena040683/nodejs-homework-rest-api pull request #1
Opened 2021-12-20 17:57 UTC by Elena040683

2021-12-20 20:58 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
почему функция асинхронная?

2021-12-20 20:59 UTC, KirillKulakow commented on model/index.js
> +  const [contact] = contacts.filter((contact) => contact.id === contactId);
что в данном случае лучше использовать find или filter? жду аргументированный ответ

2021-12-20 21:00 UTC, KirillKulakow commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body };
какой смысл перезаписывать ид?

2021-12-20 21:01 UTC, KirillKulakow requested changes
need fix

2021-12-21 21:11 UTC, Elena040683 commented on model/index.js
> +  const [contact] = contacts.filter((contact) => contact.id === contactId);
Если метод filter используется для поиска всех элементов, удовлетворяющих условию, то метод find позволяет найти и вернуть первый подходящий элемент, после чего перебор массива прекращается (т.е. ищет до первого совпадения, что в нашем случае подходит больше)

2021-12-21 21:18 UTC, Elena040683 commented on model/index.js
> +const listContacts = async () => {
Синхронные методы плохи тем, что блокируют выполнения нашего процесса, поэтому используются в крайне редких случаях. Наш код должен быть всегда асинхронным.

2021-12-21 21:20 UTC, Elena040683 commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body };
Объект прилетает с клиента без id.

2021-12-22 19:29 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
окей, принято
но синхронные методы не используются крайне редко, в основном асинхронные методы используются для того чтобы не блокировать стек задач (если этот метод выполняется достаточно долго или данный метод ожидает какой то ответ от другого сервиса)
В данном случае у тебя нет никаких асинхронный операций внутри данного метода - ты только отдаешь список контактов, так какой смысл - делать данный метод асинхронным?

2021-12-22 19:30 UTC, KirillKulakow commented on model/index.js
> +  const [contact] = contacts.find((contact) => contact.id === contactId);
здесь будет ошибка - подумай что возвращает метод find... если мысль не прийдет - напишешь в слак

2021-12-22 19:36 UTC, KirillKulakow commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body };
ок - разберем то что ты записываешь
например у тебя следующие изначальные данные такие:
```
const contacts = [{ id: 3, name: "Mark", email: "mark@test.com", phone: "333-33-33"}, { id: 1, name: "Roman", email: "roman@test.com", phone: "444-44-44"}];
body = { name: "Rick", email: "rick@gmail.com", phone: "332-12-32" };
```
contactId пусть будет 3, в итоге мы получим:
`const updatedContact = { id: 3, ...{ id: 3, name: "Mark", email: "mark@test.com", phone: "333-33-33"}, ...{ name: "Rick", email: "rick@gmail.com", phone: "332-12-32" } };`
вопрос остается - зачем перезаписывать ид?

2021-12-22 19:37 UTC, KirillKulakow requested changes
Need fix

2021-12-22 22:58 UTC, Elena040683 commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body };
Оказывается работает и без перезаписи id

2021-12-22 23:37 UTC, Elena040683 commented on model/index.js
> +  const [contact] = contacts.find((contact) => contact.id === contactId);
Метод find возвращает первый элемент, удовлетворяющий условию, когда колбек возвращает true. Если не один элемент не подойдёт, т.е. для всех элементов колбек вернул false, метод возвращает undefined.  Find используется для одной задачи поиск элементов по уникальному значению свойства.

2021-12-23 17:21 UTC, Elena040683 commented on model/index.js
> +  const [contact] = contacts.find((contact) => contact.id === contactId);
Убрала деструктуризацию.

2021-12-24 11:08 UTC, KirillKulakow approved these changes

2021-12-24 15:46 UTC, merged