Hw 03
Elena040683/nodejs-homework-rest-api pull request #2
Opened 2021-12-27 22:50 UTC by Elena040683

2021-12-28 20:28 UTC, KirillKulakow commented on .env
> +URI_DB=mongodb+srv://Star:135star135@cluster0.rvhb1.mongodb.net/MyDatabase
файл удалить из гита и добавить в гитигнор

2021-12-28 20:28 UTC, KirillKulakow commented on .vscode/launch.json
> +{
файл удалить из гита и добавить в гитигнор

2021-12-28 20:29 UTC, KirillKulakow commented on controllers/contacts/index.js
> +  console.log(contact); // toObject
зачем этот консоль?

2021-12-28 20:30 UTC, KirillKulakow commented on controllers/contacts/index.js
> +    .json({ status: "success", code: HttpCode.OK, data: { ...contacts } });
смысл этой строки `data: { ...contacts }`?

2021-12-28 20:32 UTC, KirillKulakow commented on repository/contacts.js
> +  const total = await Contact.find().countDocuments();
можно сделать операцию одним методом `await Contact.countDocuments()`

2021-12-28 20:32 UTC, KirillKulakow requested changes
Need fix

2021-12-29 17:07 UTC, Elena040683 commented on .env
> +URI_DB=mongodb+srv://Star:135star135@cluster0.rvhb1.mongodb.net/MyDatabase
Сделала. Удалила .env

2021-12-29 17:20 UTC, Elena040683 commented on .vscode/launch.json
> +{
Удалила .vscode папку  и добавила ее в гитигнор.

2021-12-29 17:30 UTC, Elena040683 commented on controllers/contacts/index.js
> +  console.log(contact); // toObject
Убираю, это на занятии мы разбирали разницу между json представлением и объектным представлением.

2021-12-29 22:22 UTC, Elena040683 commented on controllers/contacts/index.js
> +    .json({ status: "success", code: HttpCode.OK, data: { ...contacts } });
data - полезная нагрузка, представляющая собой объект.  Для красоты  возвращаемых дынных применяем спред оператор ... contacts

2021-12-30 00:25 UTC, Elena040683 commented on repository/contacts.js
> +  const total = await Contact.find().countDocuments();
Исправила.

2022-01-04 20:25 UTC, KirillKulakow commented on controllers/contacts/index.js
> +    .json({ status: "success", code: HttpCode.OK, data: { ...contacts } });
почему же просто не написать `data: contacts`?
не вижу смысла
если я не прав, поправь

2022-01-04 20:29 UTC, KirillKulakow commented on repository/contacts.js
> +  const total = await Contact.countDocuments();
И на будущее
Если тебе нужно количество записей в коллекции (без фильтра)
Намного лучше использовать функцию https://docs.mongodb.com/manual/reference/method/db.collection.estimatedDocumentCount/#mongodb-method-db.collection.estimatedDocumentCount

2022-01-04 20:30 UTC, KirillKulakow approved these changes

2022-01-04 21:13 UTC, Elena040683 commented on repository/contacts.js
> +  const total = await Contact.countDocuments();
Ok. Принято к руководству в работе.

2022-01-05 21:18 UTC, merged