Hw 04
Elena040683/nodejs-homework-rest-api pull request #3
Opened 2022-01-09 20:21 UTC by Elena040683

2022-01-10 21:40 UTC, KirillKulakow commented on controllers/auth/index.js
> +  console.log(req.body);
удалить

2022-01-10 21:48 UTC, KirillKulakow commented on routes/api/auth/index.js
> +router.post("/logout", guard, logout);
где роут current

2022-01-10 21:48 UTC, KirillKulakow requested changes
Need fix

2022-01-11 17:36 UTC, Elena040683 commented on controllers/auth/index.js
> +  console.log(req.body);
Есть. Сделала.

2022-01-11 19:26 UTC, Elena040683 commented on routes/api/auth/index.js
> +router.post("/logout", guard, logout);
Добавила роут current.

2022-01-11 20:16 UTC, KirillKulakow approved these changes

2022-01-12 18:08 UTC, merged